general:
{
   exp_dir: experiments/tlab_stage2
}

dataset:
{
   include "../../datasets/TLab/tlab_body.conf"
   collate: padding9
}

train:
{
   pretrained_ckpt: experiments/tlab_stage1/finetune_motion_body/ckpt/best_model.ckpt
   lr: 5e-5
   batch_size: 32

   rot_weight: 1e3
   pos_weight: 1e2
   vel_weight: 1e1
   cov_weight: 1e-4

   network: codenet
   gtrot:True
   propcov:True
   covaug:True
   gtinit: True

   sampling: 50
   loss: Huber_loss005
   rotloss: Huber_loss005

   min_lr: 1e-6
   max_epoches: 30
   patience: 10
   factor: 0.1
   weight_decay: 1e-4

   save_freq: 5
   eval_freq: 1
}
