train:
{
    mode: train
    calib: False
    data_list:
    [
        {name: TLab
        window_size: 200
        step_size: 4
        data_root: ./T-Lab_31st_July_dataset
        data_drive: [RAW/flight_1, RAW/flight_3, RAW/flight_5, RAW/flight_7, UN/flight_1, UN/flight_3, UN/flight_5, UN/flight_7]
        },
        {name: TLab
        window_size: 200
        step_size: 4
        data_root: ./T-Lab_28th_July_dataset
        data_drive: [RAW/flight_1, RAW/flight_2, RAW/flight_6, UN/flight_1, UN/flight_4, UN/flight_5]
        }
    ]
    gravity: 9.81007
}

test:
{
    mode: test
    calib: False
    data_list:
    [
        {name: TLab
        window_size: 200
        step_size: 4
        data_root: ./T-Lab_31st_July_dataset
        data_drive: [RAW/flight_4, RAW/flight_8, UN/flight_2, UN/flight_6]
        },
        {name: TLab
        window_size: 200
        step_size: 4
        data_root: ./T-Lab_28th_July_dataset
        data_drive: [RAW/flight_3, RAW/flight_5, UN/flight_2, UN/flight_6]
        }
    ]
    gravity: 9.81007
}

eval:
{
    mode: evaluate
    calib: False
    data_list:
    [
        {
        name: TLab
        window_size: 200
        step_size: 4
        data_root: ./T-Lab_31st_July_dataset
        data_drive: [RAW/flight_6, RAW/flight_9, UN/flight_4, UN/flight_8]
        },
        {name: TLab
        window_size: 200
        step_size: 4
        data_root: ./T-Lab_28th_July_dataset
        data_drive: [RAW/flight_4, RAW/flight_7, UN/flight_3, UN/flight_7]
        }
    ]
    gravity: 9.81007
}

inference:
{
    mode: evaluate
    calib: False
    data_list:
    [
        {
        name: TLab
        window_size: 200
        step_size: 4
        data_root: ./T-Lab_31st_July_dataset
        data_drive: [RAW/flight_1, RAW/flight_3, RAW/flight_4, RAW/flight_5, RAW/flight_6, RAW/flight_7, RAW/flight_8, RAW/flight_9, UN/flight_1, UN/flight_2, UN/flight_3, UN/flight_4, UN/flight_5, UN/flight_6, UN/flight_7, UN/flight_8]
        },
        {name: TLab
        window_size: 200
        step_size: 4
        data_root: ./T-Lab_28th_July_dataset
        data_drive: [RAW/flight_1, RAW/flight_2, RAW/flight_3, RAW/flight_4, RAW/flight_5, RAW/flight_6, RAW/flight_7, UN/flight_1, UN/flight_2, UN/flight_3, UN/flight_4, UN/flight_5, UN/flight_6, UN/flight_7]
        }
    ]
    gravity: 9.81007
}
