train:
{
    mode: train
    calib: False
    data_list:
    [
        {name: TLab
        window_size: 200
        step_size: 4
        data_root: /content/AirIMU/TL-data
        data_drive: [flight_1, flight_2, flight_10, flight_11, flight_5, flight_6, flight_7]
        },
    ]
    gravity: 9.81007
}

test:
{
    mode: test
    calib: False
    data_list:
    [
        {name: TLab
        window_size: 200
        step_size: 4
        data_root: /content/AirIMU/TL-data
        data_drive: [flight_8, flight_9, flight_3, flight_4]
        },
    ]
    gravity: 9.81007
}

eval:
{
    mode: evaluate
    calib: False
    data_list:
    [{
        name: TLab
        window_size: 200
        step_size: 4
        data_root: /content/AirIMU/TL-data
        data_drive: [flight_12, flight_13]
        },
    ]
    gravity: 9.81007
}

inference:
{
    mode: evaluate
    calib: False
    data_list:
    [{
        name: TLab
        window_size: 200
        step_size: 4
        data_root: /content/Air-IO/TL-data
        data_drive: [flight_1, flight_2, flight_3, flight_4, flight_5, flight_6, flight_7, flight_8, flight_9, flight_10, flight_11, flight_12, flight_13]
        },
    ]
    gravity: 9.81007
}
